version: "3.3"

services:
  peertube-seeder:
    image: tyrsarm/peertube-headless-seeder:v0.1 #currently no latest tag
    environment:
      api_url: "https://example.tube/api/v1/accounts/channelname/videos"
    restart: unless-stopped
